### ISSUE TITLE
problems with octopress

### ISSUE THREAD

**Issue by carloscarcamo** [mmistakes/so-simple-theme#122]
Hello, first at all thanks for this awesome theme.
I need some help! I would like to use octopress but I get errors when trying to create a post:

```shell
$ octopress new post "Hello world" --dir posts
WARN: Unresolved specs during Gem::Specification.reset:
      pygments.rb (~> 0.6.0)
      redcarpet (~> 3.1)
      jekyll-watch (~> 1.1)
      classifier-reborn (~> 2.0)
      octopress-docs (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/usr/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `require': cannot load such file -- jekyll-sitemap (LoadError)
	from /usr/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:29:in `block in require_gems'
	from /usr/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `each'
	from /usr/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:26:in `require_gems'
	from /usr/lib/ruby/gems/1.9.1/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
	from /usr/lib/ruby/gems/1.9.1/gems/octopress-3.0.0.rc.32/lib/octopress.rb:61:in `read_site'
	from /usr/lib/ruby/gems/1.9.1/gems/octopress-3.0.0.rc.32/lib/octopress.rb:52:in `site'
	from /usr/lib/ruby/gems/1.9.1/gems/octopress-3.0.0.rc.32/lib/octopress/commands/new.rb:52:in `block (3 levels) in init_with_program'
	from /usr/lib/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /usr/lib/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/lib/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /usr/lib/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /usr/lib/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /usr/lib/ruby/gems/1.9.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /usr/lib/ruby/gems/1.9.1/gems/octopress-3.0.0.rc.32/bin/octopress:16:in `<top (required)>'
	from /usr/bin/octopress:23:in `load'
	from /usr/bin/octopress:23:in `<main>'
```
I'm new with ruby, gems, jekyll and so on, any idea in what i'm doing wrong and how to fix my problem?
Thanks in advance!

**Comment by mmistakes** [comment]
Try this `bundle exec octopress new post "Hello world" --dir posts`

**Comment by carloscarcamo** [comment]
awesome, it works great! thanks for help. :+1:
