### ISSUE TITLE
invalid byte sequence in GBK. Bundler cannot continue.

### ISSUE THREAD

**Issue by shangchihh** [mmistakes/so-simple-theme#313]
## Environment

- So Simple version: 3.1.1
- Ruby gem or remote theme version: 2.7.6
- Jekyll version: 3.8.4
- Git repository URL: [https://github.com/shangchihh/shangchihh.github.io](https://github.com/shangchihh/shangchihh.github.io)
- GitHub Pages hosted (if yes provide URL to site): [https://shangchihh.github.io/](https://shangchihh.github.io/)
- Operating system: Windows

## Expected behavior

Correctly handle Chinese file names.

## Steps to reproduce the behavior

In my project, there is a file whose name is in Chinese. When I run `bundle exec jekyll serve --drafts` in local, it reports:

```
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler.rb:511:in `rescue in eval_gemspec':  (Bundler::Dsl::DSLError)
[!] There was an error parsing `Gemfile`:
[!] There was an error while loading `jekyll-theme-so-simple.gemspec`: invalid byte sequence in GBK. Bundler cannot continue.

 #  from E:/Github/shangchihh.github.io/jekyll-theme-so-simple.gemspec:14
 #  -------------------------------------------
 #    spec.add_development_dependency "rake", "~> 10.0"
 >  end
 #  # coding: utf-8
 #  -------------------------------------------
. Bundler cannot continue.

 #  from E:/Github/shangchihh.github.io/Gemfile:2
 #  -------------------------------------------
 #  source "https://rubygems.org"
 >  gemspec #  source "https://rubygems.org"
 #  -------------------------------------------
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler.rb:502:in `eval_gemspec'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler.rb:440:in `block in load_gemspec_uncached'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/shared_helpers.rb:65:in `chdir'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/shared_helpers.rb:65:in `block in chdir'
        from C:/Ruby25-x64/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/shared_helpers.rb:64:in `chdir'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler.rb:439:in `load_gemspec_uncached'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler.rb:425:in `load_gemspec'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/dsl.rb:66:in `block in gemspec'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/dsl.rb:66:in `map'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/dsl.rb:66:in `gemspec'
        from E:/Github/shangchihh.github.io/Gemfile:2:in `eval_gemfile'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/dsl.rb:47:in `instance_eval'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/dsl.rb:47:in `eval_gemfile'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/dsl.rb:12:in `evaluate'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/definition.rb:35:in `build'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler.rb:135:in `definition'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler.rb:101:in `setup'
        from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/setup.rb:20:in `<top (required)>'
        from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
```

**Comment by mmistakes** [comment]
The error messages are pointing you in the right direction

> [!] There was an error parsing `Gemfile`:
> [!] There was an error while loading `jekyll-theme-so-simple.gemspec`: invalid byte sequence in GBK. Bundler cannot continue.

1. Remove the [`.gemspec`](https://github.com/shangchihh/shangchihh.github.io/blob/master/jekyll-theme-so-simple.gemspec) file. This is not something you need and is used for building the theme gem only.
2. Setup the [`Gemfile`](https://github.com/mmistakes/so-simple-theme/blob/master/docs/Gemfile) as [directed in the theme's installation docs](https://github.com/mmistakes/so-simple-theme/blob/master/README.md#github-pages-method). Like the `.gemspec` file this is a development version.
3. Run `bundle update` after fixing 1 and 2.

Any other issues are likely related to your local Ruby environment. You'll have to research that or ask help in Jekyll's forum.

**Comment by shangchihh** [comment]
Thanks. It solves my problem.
